# Generated by Django 5.1.4 on 2025-01-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_item_category_remove_item_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
