# Generated by Django 5.1.4 on 2025-01-14 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='propertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='apartmentListingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipCode', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='individualListingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='iListing_images')),
                ('video', models.FileField(blank=True, null=True, upload_to='iListing_video')),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('is_sold', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IndividualListings', to=settings.AUTH_USER_MODEL)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='Listing.propertytype')),
            ],
        ),
        migrations.CreateModel(
            name='ListingAmentiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='Listing.amenity')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='Listing.individuallistingmodel')),
            ],
        ),
        migrations.CreateModel(
            name='optionalIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squarefeet', models.FloatField()),
                ('LaundryType', models.CharField(max_length=255)),
                ('parking', models.CharField(max_length=255)),
                ('air_Conditioning', models.CharField(max_length=255)),
                ('heating', models.CharField(max_length=255)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_details', to='Listing.individuallistingmodel')),
            ],
        ),
    ]
