# Generated by Django 5.1.4 on 2026-04-04 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listing', '0002_apartmentlistingmodel_is_approved_apartmentunit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_token', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_views', to='Listing.individuallistingmodel')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('viewer__isnull', False)), fields=('listing', 'viewer'), name='unique_listing_view_per_user'), models.UniqueConstraint(condition=models.Q(('viewer__isnull', True), models.Q(('visitor_token', ''), _negated=True)), fields=('listing', 'visitor_token'), name='unique_listing_view_per_visitor_token')],
            },
        ),
    ]
